"""start

Revision ID: 509eed7a513a
Revises: 
Create Date: 2018-12-04 14:20:47.473679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509eed7a513a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RaceStats',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=20), nullable=False),
    sa.Column('race_weight', sa.Integer(), nullable=False),
    sa.Column('race_monster', sa.Boolean(), nullable=False),
    sa.Column('stat_bonus_2', sa.String(length=3), nullable=True),
    sa.Column('stat_bonus_1', sa.String(length=3), nullable=True),
    sa.Column('str_weight', sa.Integer(), nullable=False),
    sa.Column('con_weight', sa.Integer(), nullable=False),
    sa.Column('dex_weight', sa.Integer(), nullable=False),
    sa.Column('int_weight', sa.Integer(), nullable=False),
    sa.Column('wis_weight', sa.Integer(), nullable=False),
    sa.Column('cha_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('race_id')
    )
    op.create_table('Skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=56), nullable=False),
    sa.Column('skill_stat', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('BackStats',
    sa.Column('back_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('back_name', sa.String(length=50), nullable=False),
    sa.Column('back_weight', sa.Integer(), nullable=False),
    sa.Column('back_stat', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['RaceStats.race_id'], ),
    sa.PrimaryKeyConstraint('back_id')
    )
    op.create_table('ClassStats',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('back_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=56), nullable=False),
    sa.Column('preferred_stat', sa.String(length=3), nullable=True),
    sa.Column('preferred_stat_2', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['back_id'], ['BackStats.back_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['RaceStats.race_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('ClassSkills',
    sa.Column('class_skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['ClassStats.class_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['Skills.skill_id'], ),
    sa.PrimaryKeyConstraint('class_skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClassSkills')
    op.drop_table('ClassStats')
    op.drop_table('BackStats')
    op.drop_table('Skills')
    op.drop_table('RaceStats')
    # ### end Alembic commands ###
